name: "Mutli Event Pipeline"
on:
    push:
        branches:
            - main
            - test
jobs:
      on-push:
        runs-on: ubuntu-latest
        steps:
            - name: "Running on main/test push"
              run: echo "Running on main push"
            
        
