name: "Mutli Event Pipeline"
on:
    push:
        branches:
            - main
            - test
    pull_request:
        branches:
            - main
jobs:
      on-push:
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
            - name: "Running on main/test push"
              run: echo "Running on main push"
      on-pull:
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps:
            - name: "Running on main pull"
              run: echo "Running on main pull"
            
        
